name = "tardi"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

# Preview environment (dev deployments via --branch=dev)
[env.preview.vars]
COMING_SOON = "false"
API_URL = "https://tardi-api-dev-lckw22k4gq-uc.a.run.app"
VITE_USE_MOCK_AUTH = "false"
VITE_USE_MOCK = "false"
VITE_FIREBASE_API_KEY = "AIzaSyC6qEnkLZn09RBWg1oAekZ2s8QabtpBIqE"
VITE_FIREBASE_AUTH_DOMAIN = "tardi-dev-488420.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "tardi-dev-488420"
VITE_FIREBASE_STORAGE_BUCKET = "tardi-dev-488420.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "303646674262"
VITE_FIREBASE_APP_ID = "1:303646674262:web:ffb1dda130db33b18d5af7"
STRIPE_PRICING_TABLE_ID = "prctbl_1TCbHLAPpIsY1S3ukYSMQ12U"
STRIPE_PUBLISHABLE_KEY = "pk_test_51T4zbdAPpIsY1S3u2sy8FJ5ehbYHGoWfqGJ7lkO5y5y8h3zZ3hO2e5I8jqRZ0PNMFFwWSSxc86oHJBw2BBt0hYbG00PJI8lpMT"
GOOGLE_SHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbwLtsPQeta-1SvGb0zG5aNST1NRQgqC4p3fevmt5rS5P5RbfNQfngivC6lc9pWIMtpu/exec"
VITE_SENTRY_DSN = "https://7b373dad914fe78ef8b1a523ac29e821@o4511031391813632.ingest.us.sentry.io/4511031394893824"
VITE_SENTRY_ENVIRONMENT = "dev"
VITE_FF_MODEL_SELECTION = "false"

# Production environment
[env.production.vars]
COMING_SOON = "false"
API_URL = "https://tardi-api-prod-vyqbffpjya-uc.a.run.app"
VITE_USE_MOCK_AUTH = "false"
VITE_USE_MOCK = "false"
VITE_FIREBASE_API_KEY = "AIzaSyBseyK0nQ9xiS0K7uL_x84AzTjBpUtyKoI"
VITE_FIREBASE_AUTH_DOMAIN = "tardi-prod-488420.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "tardi-prod-488420"
VITE_FIREBASE_STORAGE_BUCKET = "tardi-prod-488420.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "1043193293599"
VITE_FIREBASE_APP_ID = "1:1043193293599:web:bca40f2d944e1b3021de2a"
STRIPE_PRICING_TABLE_ID = "prctbl_1TCcpDAPpIsY1S3uNc56TmIk"
STRIPE_PUBLISHABLE_KEY = "pk_live_51T4zbdAPpIsY1S3uhXUlmD6YrvqeDCaoLRlimvXNgvaIRfIDHeJhnMCVmNTLhfBwk0pzsmEGnaisK7vk2DcMNx2p00f0sGqP29"
GOOGLE_SHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbwLtsPQeta-1SvGb0zG5aNST1NRQgqC4p3fevmt5rS5P5RbfNQfngivC6lc9pWIMtpu/exec"
VITE_SENTRY_DSN = "https://7b373dad914fe78ef8b1a523ac29e821@o4511031391813632.ingest.us.sentry.io/4511031394893824"
VITE_SENTRY_ENVIRONMENT = "production"
VITE_FF_MODEL_SELECTION = "false"
